### ISSUE TITLE
version in package.json?

### ISSUE THREAD

**Issue by sirudog** [TNG/sinon-helpers#14]
Hi,

Would it be possible to keep the version in package.json checked-in? I know that semantic-release does this on publishing a new release, but it would be also handy to have it in the github repo. Then one could also get a bundle by cloning the repo, npm install and npm pack. (This is my current pipeline, which fails on npm pack step as the version is missing)

**Comment by lukastaegert** [comment]
Hi,

I've just been going through the documentation for semantic-release and I don't think this can be easily accomplished without rewriting semantic-release as it basically handles the whole pipeline from push to release and I am not planning on replacing it since it is such a time-saver.
So I wonder, why do you have this workflow - which is certainly somewhat uncommon - instead of installing directly from npm? Maybe there is another way to accomplish what you are after? Beyond that, I fear your best bet is to manually add the version number after cloning the repo.

**Comment by sirudog** [comment]
Hi,

Thanks for looking into this. I have accomplished what I wanted by getting the package from this URL: `https://registry.npmjs.org/sinon-helpers/-/sinon-helpers-$version.tgz`.

This tarball has the version in package.json so my "unusual" workflow works. 
This workflow makes sure I have my direct dependencies packaged in a tarball on my dedicated server, so I can just `npm install` them from there instead of nagging npmjs.org on every build. This tarball also contains the snapshot of the dependency tree of each library my projects depend on. I guess npm-shrinkwrap partly covers this scenario, but it still hits npmjs.org every time AFAIK. So I only need this workflow when I have a new dependency, or when I want to upgrade one of my dependent libraries (I run this workflow targeting the new version of the library)

**Comment by lukastaegert** [comment]
Glad this works for you and thanks for the heads-up, this might be useful for other people that struggle with semantic-version. For your setup, maybe you also want to look into this: https://yarnpkg.com/blog/2016/11/24/offline-mirror
